service: lambda-function-boilerplate

# required for fetching env values from .env files
useDotenv: true
plugins:
  - serverless-dotenv-plugin

provider:
  runtime: nodejs20.x
  memorySize: 128
  timeout: 3
  logRetentionInDays: 1
  # only applicable if you are using layers. (Recommended Approach)
  layers:
    - ${env:LAYER_ARN}
  architecture: x86_64

  name: aws
  stage: prod
  region: us-east-1
  tags:
    boilerplate_lambda: PROD  # configure your own tag for cost exploration.

# Only if you are using layers, you should exclude this files and folder from deployment package.
package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - yarn.lock

functions:
  hello:
    handler: src/handler.handler
